Replace Knox with aws-sdk
keystonejs/keystone-storage-adapter-s3 pull request #35
Opened 2018-06-15 12:31 UTC by mikehazell

### Overview

The Knox library which this package was previously based on has gone unmaintained for some time and is now failing in many scenarios. This version replaces Knox with the official [AWS Javascript SDK](https://aws.amazon.com/sdk-for-node-js/).

### Breaking changes

The option `headers` has been replaced with `uploadParams`. If you were setting custom headers with previous version of the S3 Storage Adapter you will need to change these to use the appropriate `param` as defined in the [AWS Documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload)

For example, `{ headers: { 'x-amz-acl': 'public-read' } }` should now be `{ uploadParams: { ACL: 'public-read' } }`.

### Additions

- **publicUrl**: You can now customise the public url by passing either a domain name as a string (eg. `{ publicUrl: "https://xxxxxx.cloudfront.net" }`) or by passing a function which takes the `file` object and returns a the url as a string.
```js
{ publicUrl: file => `https://xxxxxx.cloudfront.net${file.path}/${file.filename}` }
```

### Other

- **path**: The requirement for `path` to have a **leading slash** has been removed. The previous implementation failed to catch this miss-configuration and Knox helpfully made the file uploads work anyway. This has lead to a situation where it is possible/likely that there are existing installations where a miss-configured path is stored in the database. To avoid breaking these installs we now handle adding or removing the leading slash as required.

2018-06-15 13:00 UTC, alsoicode commented
+1 for this. Nice work.

2018-06-16 07:43 UTC, dominikwilkowski requested changes
Looks awesome, Thanks @mikehazell; love the comments!

2018-06-16 07:43 UTC, dominikwilkowski commented on index.js
> +	if (file && file.bucket && file.bucket) {
probably don't need `file.bucket` twice here?

2018-06-16 07:43 UTC, dominikwilkowski commented on package.json
>    },
We should version bump the package no? `"version": "2.0.0",` on line 3.

2018-06-18 03:28 UTC, dominikwilkowski approved these changes

2018-06-18 03:28 UTC, merged